### ISSUE TITLE
Page edit not working

### ISSUE THREAD

**Issue by denvash** [facebookresearch/balance#12]
Hi team! Here is your first issue:

On trying to edit any wiki page it redirects to non existing page.

<img width="840" alt="image" src="https://user-images.githubusercontent.com/27515937/204734790-73875406-7f7e-43ed-9454-eaf7cc3dfbde.png">

<img width="740" alt="image" src="https://user-images.githubusercontent.com/27515937/204734902-8d153381-a157-4b70-84a2-002d7997c533.png">

**Comment by stevemandala** [comment]
Should be resolved now via #14
