### ISSUE TITLE
Incompatible with Python 3.11

### ISSUE THREAD

**Issue by tomwagstaff-opml** [facebookresearch/balance#19]
I'm unable to pip install this package in a clean environment with Python 3.11 installed on my machine. The problem seems to be the dependency on `scipy<=1.8.1`. The maximum version (1.8.1) is only compatible with Python versions 3.8 - 3.10.

Scipy v1.6.1 is not flagged as incompatible with Python 3.11, and is the version picked automatically when I `pip install balance`. However, this fails with the error, `metadata-generation-failed` - which also seems to be a [versioning issue](https://stackoverflow.com/questions/70916814/error-metadata-generation-failed-cant-install-artic-module). I suspect _all_ versions of `scipy` prior to 1.9.0 are incompatible with Python 3.11.

**Request: can you make the package compatible with scipy v1.10.0 please?** (which installs in Python 3.11 with no problems)

Failing that, can anyone suggest any workarounds?

**Comment by talgalili** [comment]
Hey @tomwagstaff-opml 

This is an issue because of the dependancy of the IPW implementation on glmnet (which is getting to be old at this point).
We plan to move to sklearn by June, but that will take some time.

In the meantime, would using the package only with CBPS be good enough for your needs?
(Because if so, there is a hack we can discuss)

**Comment by tomwagstaff-opml** [comment]
Hi @talgalili !

Thanks for your speedy response.

Understand the constraint, and looking around it looks like the easiest solution is probably for me to roll back to Python 3.9 or something, so I'm working on that...

Having said that - my main interest in the package was road-testing CBPS (although I wanted to try all the methods it offers). So if there's an (easy) hack I'd be all ears :-)

**Comment by talgalili** [comment]
The hack (which I'm not sure how easy), is to fork the repo, manually change the setup.py to not restrict you to scipy 1.18, and then install the package from the fork.
You might also need to remove the dependancy on glmnet.

I haven't tried it, but I think it's worth a shot.

If you try it, could you please share how it went?

(P.s., whenever invoking sample.adjust you'll need to use method="cbps", since the default of "ipw" will not work)

**Comment by talgalili** [comment]
For our iwn reference, solving this issue depends on solving:
https://github.com/facebookresearch/balance/issues/16

**Comment by stevemandala** [comment]
Adding to @talgalili's summary, the main reason we pinned the scipy dependency is that glmnet_python relies on several scipy libraries that were deprecated & moved in 1.9.0 (full release notes [here](https://docs.scipy.org/doc/scipy/release.1.9.0.html#expired-deprecations)). Top of mind, glmnet_python relies on 
 `scipy.random` at [several code pointers](https://github.com/bbalasub1/glmnet_python/search?q=scipy.random)

While resolving https://github.com/facebookresearch/balance/issues/16 would be the ideal mitigation, another route would be to migrate glmnet_python source to also support scipy 1.9.0+, e.g. migrating `scipy.random` to `numpy.random`. I submitted an issue at https://github.com/bbalasub1/glmnet_python/issues/64 for tracking this.

**Comment by tomwagstaff-opml** [comment]
Thanks both - this all makes sense, and it doesn't sound quick or easy to address from your side (although I guess it's something you'll have to grapple with sooner or later). I'm happy to get hold of another version of Python to play with the package

**Comment by talgalili** [comment]
Thanks @tomwagstaff-opml 

The good news os that we continued to discuss this internally and we might have a dorection of how to monkey-patch this problem (thanks to the wonderful @stevemandala ).
It's still being tested. We'll update here once we find something that seems to work. (Hopefully today but it might only get to happen next week).

T

**Comment by talgalili** [comment]
@tomwagstaff-opml great news:
@stevemandala just landed a patch to make balance support 3.11.
Could you please test to see if it works for you by installing it via:
```
python -m pip install git+https://github.com/facebookresearch/balance.git
```
And let us know how it goes?

**Comment by tomwagstaff-opml** [comment]
Oh gosh - I just had IT roll back my Python installation! I'll see if I can create a 3.11 environment to test it - but either way, thanks very much for your efforts @stevemandala

**Comment by talgalili** [comment]
Sorry @tomwagstaff-opml 
We didn't expact @stevemandala to find a solution that fast :D

**Comment by tomwagstaff-opml** [comment]
I've tried installing and I'm afraid it refused to install in Python 3.11 :-(

Just to recap what I did - after the rollback I got miniconda installed and created a Python 3.11 environment to test the package. I `conda install`ed git, and then tried to `pip install`  balance as per your command. It fails to install, with this really weird character encoding error, so who knows if that's real or a red herring...

The good news is I created a Python 3.10 environment and successfully pip installed `balance` there - just from PyPi. I ran into the same error as below when I tried to install from GitHub, so maybe that's a clue as to where the problem is.

```
Cloning https://github.com/facebookresearch/balance.git to c:\users\twagstaff\appdata\local\temp\pip-req-build-feduampl
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/balance.git 'C:\Users\twagstaff\AppData\Local\Temp\pip-req-build-feduampl'
  Resolved https://github.com/facebookresearch/balance.git to commit c6f056f91a238b70cddccc97e685d6a654a91a63
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\twagstaff\AppData\Local\Temp\pip-req-build-feduampl\setup.py", line 90, in <module>
          setup_package()
        File "C:\Users\twagstaff\AppData\Local\Temp\pip-req-build-feduampl\setup.py", line 55, in setup_package
          long_description = fh.read()
                             ^^^^^^^^^
        File "C:\Users\twagstaff\AppData\Local\miniconda3\envs\balance_311\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1494: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

```

**Comment by talgalili** [comment]
Thanks @tomwagstaff-opml 

Just to double check, you used this code:

python -m pip install git+https://github.com/facebookresearch/balance.git

?

**Comment by tomwagstaff-opml** [comment]
Yes indeed - well actually just the `pip install...` bit as I don't think I need to explicitly call python again once I'm in the environment

**Comment by talgalili** [comment]
Fascinating. Especially given that it runs fine on gh actions under 3.11.
What I think we might do is later today release balance 0.3.0 (which should support 3.11). Once it gets to pypi I'll ping here again and you can try installing it through pypi.

Thanks for helping us debug this.

**Comment by stevemandala** [comment]
@tomwagstaff-opml As @talgalili mentioned, this should be resolved for PyPi installs with the new release. I also have a quick fix for the `UnicodeDecodeError` error as well, which was due to errors when decoding the utf-8 files on Windows: https://github.com/facebookresearch/balance/pull/28

This should fix the issue with builds from source directly

(Also want to echo Tal's thank you for your help raising and debugging these issues!)

**Comment by talgalili** [comment]
@tomwagstaff-opml - update: we've now landed a fix that should make installing from github on windows possible again.
Would you please try to reinstall balance on 3.11 from your windows machine using the github repo?

**Comment by tomwagstaff-opml** [comment]
I'm afraid that failed again, but I don't think it's on you.

The problem now is the dependency on `pandas`. If I try to conda install it, I'm told it's not available for Python 3.11 - I think that must be a specific issue with the conda repos because it's listed as [compatible on PyPi](https://pyreadiness.org/3.11/).

If I try to pip install `balance` - and let pip take care of the pandas dependency - I'm prompted to install C++ first, which I'm afraid is an IT ticket too far for me 😅

**Comment by talgalili** [comment]
Oh my.
@tomwagstaff-opml :
We currently require `pandas<=1.4.3`. Is the issue that we need to make sure we support pandas 1.5.0 or some other version?

(Please let us know - I'd be happy to open a ticket for this as well)

**Comment by tomwagstaff-opml** [comment]
Ahh, I think it might be - I'm using pandas 1.4.3. in the Python 3.10 environment...

**Comment by talgalili** [comment]
Ok, so it's not clear to me what's broken then :(

I suggest we leave this issue closed, and if you come across more issues - feel free to open new issues for them.
