### ISSUE TITLE
module 'balance.adjustment' has no attribute 'apply_transformations'

### ISSUE THREAD

**Issue by Sourabhmehta-AIM** [facebookresearch/balance#20]
Just trying the CBPS sample notebook and ran up this error.
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-58-ee26876ffb7a>](https://localhost:8080/#) in <module>
----> 1 adjusted_cbps = sample_with_target.adjust(method = "cbps")

1 frames
[/usr/local/lib/python3.8/dist-packages/balance/weighting_methods/cbps.py](https://localhost:8080/#) in cbps(sample_df, sample_weights, target_df, target_weights, variables, transformations, na_action, formula, balance_classes, cbps_method, max_de, opt_method, opt_opts, weight_trimming_mean_ratio, weight_trimming_percentile, random_seed, *args, **kwargs)
    434     # should be transformed with the *identity function*,
    435     # otherwise will be dropped from the model
--> 436     sample_df, target_df = balance_adjustment.apply_transformations(
    437         (sample_df, target_df), transformations=transformations
    438     )

AttributeError: module 'balance.adjustment' has no attribute 'apply_transformations'
```

**Comment by SarigT** [comment]
Thank you for reporting, I'll look into this

**Comment by talgalili** [comment]
Hey @Sourabhmehta-AIM 
I just ran the entire notebook and couldn't reproduce this error you report.
Here is what I got:

![image](https://user-images.githubusercontent.com/976006/215085333-48153075-7a34-4e01-8901-223bcb599810.png)

Could you please help us debug this by sharing your session information?
Here is a nice resource for how to do it:
https://stackoverflow.com/a/31906216/256662

Steps:
1 - run
`pip install session-info`
2 - from the notebook, after the failure, run:
`session_info.show()`
3 - copy-paste the output into a comment here.

Thanks for the report :)

**Comment by Sourabhmehta-AIM** [comment]
Hey @talgalili, sure, let me try to get the reports. I could also share my notebook and the data which was used while experimenting.

**Comment by talgalili** [comment]
Hey @Sourabhmehta-AIM 
Just to verify - you closed the issue because you managed to get it to work?

**Comment by Sourabhmehta-AIM** [comment]
Yeah, I reinstalled the package, and it worked, but I will dig further and try to find out why that issue occurred. If and would like to add one point just add a markdown that says install `glmnet_py`. Because am using colab for the experiment and it requires installation. 
Thanks for the time and quick response, great work!

**Comment by talgalili** [comment]
Thabks for letting us know :)
As for the readme, feel free to suggest a PR for where to add it, and we'll review it.

Cheers,
T

**Comment by Sourabhmehta-AIM** [comment]
Sure @talgalili I would add the PR in this thread.

Regards,
S

**Comment by talgalili** [comment]
For reference, this also happened here:
https://github.com/facebookresearch/balance/issues/27
And was resolved when the app was re-installed.
