### ISSUE TITLE
Can't use `method = "cbps"` (windows, Python 3.10)

### ISSUE THREAD

**Issue by tomwagstaff-opml** [facebookresearch/balance#27]
And yet another - I'm so sorry...

Also just trying to complete the quick start example in a Python 3.10 environment, I just tried switching the method, so running this line instead:

`adjusted_cbps = sample_with_target.adjust(method = "cbps")`

This fails with the following error:

`AttributeError: module 'balance.adjustment' has no attribute 'apply_transformations'`

Sorry I have no guesses as to what's causing this one.

**Comment by talgalili** [comment]
Thanks for the report @tomwagstaff-opml !
So interesting.

Some thoughts:
1. Could you please run in your bento the following code, and paste here the output?

```
# Sessions info
import session_info
session_info.show(html=False, dependencies=True)
```

2. In your bento, could you please run:
```
import balance
dir(balance.adjustment)
```
And paste the input you get?

**Comment by talgalili** [comment]
For reference, here is the output I get:
```
import balance
dir(balance.adjustment)


['BALANCE_WEIGHTING_METHODS',
 'Callable',
 'Dict',
 'List',
 'Literal',
 'Tuple',
 'Union',
 '__annotations__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_find_adjustment_method',
 'absolute_import',
 'apply_transformations',
 'balance_adjust_null',
 'balance_cbps',
 'balance_ipw',
 'balance_poststratify',
 'balance_util',
 'default_transformations',
 'division',
 'is_bool_dtype',
 'is_numeric_dtype',
 'logger',
 'logging',
 'np',
 'pd',
 'print_function',
 'scipy',
 'trim_weights',
 'unicode_literals']
```

**Comment by tomwagstaff-opml** [comment]
Sure thing, @talgalili 

### Sessions info
```
-----
balance             0.2.0
pandas              1.4.3
session_info        1.0.0
-----
IPython             8.9.0
PIL                 9.4.0
asttokens           NA
backcall            0.2.0
beta_ufunc          NA
binom_ufunc         NA
coxnet              NA
cvcompute           NA
cvelnet             NA
cvfishnet           NA
cvglmnet            NA
cvglmnetCoef        NA
cvglmnetPredict     NA
cvlognet            NA
cvmrelnet           NA
cvmultnet           NA
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.2
decorator           5.1.1
elnet               NA
executing           1.2.0
fishnet             NA
glmnet              NA
glmnetCoef          NA
glmnetControl       NA
glmnetPredict       NA
glmnetSet           NA
glmnet_python       NA
hypergeom_ufunc     NA
jedi                0.18.2
joblib              1.2.0
kiwisolver          1.4.4
loadGlmLib          NA
lognet              NA
matplotlib          3.6.3
mpl_toolkits        NA
mrelnet             NA
nbinom_ufunc        NA
nt                  NA
numpy               1.24.1
packaging           23.0
parso               0.8.3
patsy               0.5.3
pickleshare         0.7.5
pkg_resources       NA
plotly              5.13.0
prompt_toolkit      3.0.36
pure_eval           0.2.2
pygments            2.14.0
pyparsing           3.0.9
pytz                2022.7.1
rpycall             NA
rpytools            NA
scipy               1.8.1
seaborn             0.11.1
setuptools          65.6.3
six                 1.16.0
sklearn             1.2.1
stack_data          0.6.2
statsmodels         0.13.5
tenacity            NA
threadpoolctl       3.1.0
traitlets           5.9.0
wcwidth             0.2.6
wtmean              NA
-----
Python 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.19044-SP0
-----
Session information updated at 2023-01-30 17:49
```

### balance.adjustment
Here I seem to get the same results as you:
```
['BALANCE_WEIGHTING_METHODS', 'Callable', 'Dict', 'List', 'Literal', 'Tuple', 'Union', '__annotations__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_find_adjustment_method', 'absolute_import', 'apply_transformations', 'balance_adjust_null', 'balance_cbps', 'balance_ipw', 'balance_poststratify', 'balance_util', 'default_transformations', 'division', 'is_bool_dtype', 'is_numeric_dtype', 'logger', 'logging', 'np', 'pd', 'print_function', 'scipy', 'trim_weights', 'unicode_literals']
```

**Comment by tomwagstaff-opml** [comment]
Hi @talgalili,

So I re-installed balance, and it worked! 😅 I can now use the CBPS method and reproduce the results for that method in the [quickstart script](https://import-balance.org/docs/tutorials/quickstart_cbps/).

The only thing that's an issue now is that some of the plots don't output - it seems to be the ones based on Seaborn, so these lines:
```
adjusted_cbps.covars().plot(library = "seaborn", dist_type = "kde")
adjusted_cbps.outcomes().plot()
```

They don't throw any error when I run them, there's just no output. 🤷 
But since I can output the adjusted dataset I'm sure I can reproduce them another way - this is just an FYI.
Thanks so much for your help and suggestions - we got there in the end!

**Comment by talgalili** [comment]
Hey @tomwagstaff-opml - I'm glad to hear that re-installing balance worked for you!

Some followup question:
1. did you re-install it using pypi or github?
2. Which Python version did you use for this install? (3.10, or 3.11?)
3. Could you please open a new issue for the seaborn plots not working? In it, could you share the output of your session_info from the ipynb (so we could see which version are together there, and see if we can understand where this is coming from)?

Thanks!

**Comment by tomwagstaff-opml** [comment]
No worries @talgalili,

1. Installed it from PyPi
2. In a Python 3.10 environment

And I'll post another issue about the seaborn plots

**Comment by talgalili** [comment]
Thanks @tomwagstaff-opml - now we have a reference for the next person who asks about it.

:)
