### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by adelchi91** [facebookresearch/balance#45]
Running the following code line 

from balance import Sample

results in the following error message:

ModuleNotFoundError: No module named 'cvglmnet'

Installation of the required module is not possible on WSL 2 despite running it with pip (see below)

ERROR: Could not find a version that satisfies the requirement cvglmnet (from versions: none)
ERROR: No matching distribution found for cvglmnet

The module does not seem to exist anywhere.

**Comment by adelchi91** [comment]
Hi, 

thanks for your quick reply. The problem seems indeed related the glmnet python package. 

I did not run 

`python -m pip install git+https://github.com/bbalasub1/glmnet_python.git@1.0`

but I seem to have fixed it by running 

` pip install glmnet_py` instead of ` pip install glmnet`

**Comment by talgalili** [comment]
Thanks @adelchi91 for taking a look and updating here.
I hope you'll enjoy the package, please let us know if you have any further questions/issues.
